#23.96.114.177
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://${PET_FEEDER_DB_ENDPOINT}/pet_feeder?&useUnicode=true&charaterEncoding=utf-8

cv-server:
  endpoint: ${CV_ENDPOINT}
